apiVersion: apps/v1
kind: Deployment
metadata: { name: dispatcher, namespace: platform }
spec:
  replicas: 2
  selector: { matchLabels: { app: dispatcher } }
  template:
    metadata: { labels: { app: dispatcher } }
    spec:
      containers:
        - name: openresty
          image: dispatcher:latest
          imagePullPolicy: IfNotPresent

          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          env:
            - { name: ROUTE_SIGNING_SECRET, valueFrom: { secretKeyRef: { name: app-secrets, key: ROUTE_SIGNING_SECRET } } }
            - name: MANAGER_SVC
              value: "http://managersvc.platform.svc.cluster.local:8000"
            - name: AUTH_SVC
              value: "http://authsvc.platform.svc.cluster.local:8000"
          ports: [{ containerPort: 8080 }]
          readinessProbe: { httpGet: { path: "/healthz", port: 8080 }, initialDelaySeconds: 2, periodSeconds: 5 }

---
apiVersion: v1
kind: Service
metadata: { name: dispatcher, namespace: platform }
spec:
  selector: { app: dispatcher }
  ports: [{ port: 80, targetPort: 8080 }]
