apiVersion: v1
kind: ServiceAccount
metadata: { name: managersvc-sa, namespace: platform }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: { name: manager-user-stack }
rules:
  - apiGroups: ["", "apps"]
    resources: ["namespaces","services","deployments","deployments/scale","pods"]
    verbs: ["get","list","watch","create","delete","patch","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: { name: manager-user-stack-binding }
subjects:
  - kind: ServiceAccount
    name: managersvc-sa
    namespace: platform
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: manager-user-stack
