apiVersion: v1
kind: Secret
metadata: { name: app-secrets, namespace: platform }
type: Opaque
stringData:
  DJANGO_SECRET: "change-me"
  JWT_SECRET: "jwt-secret-prod"
  ROUTE_SIGNING_SECRET: "route-sign-prod"
