# Generated by Django 5.2.5 on 2025-08-31 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('EXPORT', '导出'), ('IMPORT', '导入'), ('VERSION', '版本变更'), ('ROLLBACK', '回滚')], max_length=20)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.IntegerField()),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'AuditLog',
            },
        ),
        migrations.CreateModel(
            name='ResourceImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('MAP', 'Map全量导入'), ('LAYER', 'Layer增量导入')], max_length=10)),
                ('imported_data', models.JSONField(help_text='导入的JSON数据')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('SUCCESS', '成功'), ('FAILED', '失败')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('logs', models.JSONField(blank=True, default=dict, help_text='导入过程日志及差异快照')),
                ('target_layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_import_jobs', to='db.layer')),
                ('target_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_import_jobs', to='db.map')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '资源导入任务',
                'verbose_name_plural': '资源导入任务',
            },
        ),
        migrations.CreateModel(
            name='MapArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(help_text='该快照对应的 Map 版本号')),
                ('snapshot', models.JSONField(help_text='导出的 Map 完整 JSON（包含 layers）')),
                ('author', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='db.map')),
            ],
            options={
                'verbose_name': '地图归档',
                'verbose_name_plural': '地图归档',
                'db_table': 'MapArchive',
                'unique_together': {('map', 'version_number')},
            },
        ),
    ]
