# Generated by Django 5.2.5 on 2025-08-31 13:14

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '__first__'),
        ('manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapVersionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_snapshots', to='db.map')),
                ('to_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_snapshots', to='db.map')),
            ],
            options={
                'verbose_name': '地图版本快照',
                'verbose_name_plural': '地图版本快照',
                'db_table': 'MapVersionSnapshot',
            },
        ),
        migrations.CreateModel(
            name='LayerVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='db.layer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('layer', 'version')},
            },
        ),
    ]
