apiVersion: v1
kind: ServiceAccount
metadata:
  name: django-sa
  namespace: user-health   
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: django-k8s-manager
  namespace: user-health
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","list","create","patch","delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: django-k8s-manager-binding
  namespace: user-health 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: django-k8s-manager
subjects:
- kind: ServiceAccount
  name: django-sa
  namespace: user-health
