apiVersion: v1
kind: Secret
metadata:
  name: influx-secrets
  namespace: realtime
type: Opaque
stringData:
  INFLUX_TOKEN: "dev-super-token" # 生产请改为 strong token
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-env
  namespace: realtime
data:
  DEBUG: "0"
  SECRET_KEY: "please-change"
  INFLUX_URL: "http://influxdb.realtime.svc.cluster.local:8086"
  INFLUX_ORG: "dev-org"
  INFLUX_BUCKET: "dev-bucket"
  MEASUREMENT: "metrics"
  DATA_START_TS: "2024-08-01T00:00:00Z"
  DATA_END_TS:   "2024-08-01T01:00:00Z"
  DEFAULT_WINDOW_SEC: "10"
  CHANNELS_REDIS_URL: "redis://redis.realtime.svc.cluster.local:6379/0"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seed-job-script
  namespace: realtime
data:
  seed_data.py: |
    import os, datetime, random, time
    from influxdb_client import InfluxDBClient, Point, WritePrecision

    url = os.getenv("INFLUX_URL")
    token = os.getenv("INFLUX_TOKEN")
    org = os.getenv("INFLUX_ORG")
    bucket = os.getenv("INFLUX_BUCKET")

    client = InfluxDBClient(url=url, token=token, org=org)
    write_api = client.write_api()

    now = datetime.datetime.utcnow()
    for i in range(3600):  # 一小时
        point = Point("demo") \
            .field("value", random.randint(0, 100)) \
            .time(now - datetime.timedelta(seconds=3600 - i), WritePrecision.S)
        write_api.write(bucket, org, point)
        time.sleep(0.01)  # 模拟写入速率

    client.close()
