apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: realtime
spec:
  selector: { app: backend }
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: realtime
spec:
  replicas: 1
  selector: { matchLabels: { app: backend } }
  template:
    metadata: { labels: { app: backend } }
    spec:
      containers:
        - name: backend
          image: realtime-backend:1.0.0  # 替换为你的镜像
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8000 }]
          envFrom:
            - configMapRef: { name: backend-env }
            - secretRef:    { name: influx-secrets }
          # readinessProbe:
          #   httpGet: { path: /health, port: 8000 }
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet: { path: /health, port: 8000 }
          #   initialDelaySeconds: 15
          #   periodSeconds: 20
