apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-management-sa
  namespace: user-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user-management-role
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-management-binding
subjects:
- kind: ServiceAccount
  name: user-management-sa
  namespace: user-platform
roleRef:
  kind: ClusterRole
  name: user-management-role
  apiGroup: rbac.authorization.k8s.io