apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: user-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        image: auth-service:1.0
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY
          value: "django-insecure-auth-service"
        - name: DEBUG
          value: "False"
        - name: DB_ENGINE
          value: "django.db.backends.mysql"
        - name: DB_NAME
          value: "user_management"
        - name: DB_USER
          value: django
        - name: DB_PASSWORD
          value: password
        - name: DB_HOST
          value: "mysql-service.user-platform.svc.cluster.local"
        - name: DB_PORT
          value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: user-platform
spec:
  selector:
    app: auth-service
  ports:
  - port: 80
    targetPort: 8000