apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: django-celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        image: django-app:latest
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: DJANGO_SETTINGS_MODULE
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: MYSQL_PASSWORD
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: MYSQL_HOST
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: MYSQL_PORT
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: REDIS_PORT
        - name: REDIS_DB
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: REDIS_DB
        - name: REDIS_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: REDIS_PASSWORD
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: RABBITMQ_HOST
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: RABBITMQ_PORT
        - name: RABBITMQ_VHOST
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: RABBITMQ_VHOST
        - name: RABBITMQ_USER
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: RABBITMQ_USER
        - name: RABBITMQ_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: RABBITMQ_PASSWORD
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DJANGO_SECRET_KEY
        # 容器启动时自动启动Supervisor，无需手动命令
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: django-celery
spec:
  selector:
    app: django-app
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080