apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  namespace: django-celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
      - name: celery-beat
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        image: docker_test/worker:latest
        env:
        - name: DJANGO_SETTINGS_MODULE
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: DJANGO_SETTINGS_MODULE
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: MYSQL_PASSWORD
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: MYSQL_HOST
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: MYSQL_PORT
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: REDIS_PORT
        - name: REDIS_DB
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: REDIS_DB
        - name: REDIS_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: REDIS_PASSWORD
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: RABBITMQ_HOST
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: RABBITMQ_PORT
        - name: RABBITMQ_VHOST
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: RABBITMQ_VHOST
        - name: RABBITMQ_USER
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: RABBITMQ_USER
        - name: RABBITMQ_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: RABBITMQ_PASSWORD
        - name: DJANGO_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: DJANGO_SECRET_KEY
        volumeMounts:
        - name: celery-beat-data
          mountPath: /data
      volumes:
      - name: celery-beat-data
        emptyDir: {}
      # 容器启动时自动启动Supervisor，无需手动命令
        # command: ["celery", "-A", "core", "beat", "--loglevel=info"]