apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: metallb-system
  labels:
    app: metallb
    component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metallb
      component: controller
  template:
    metadata:
      labels:
        app: metallb
        component: controller
    spec:
      serviceAccountName: metallb-controller  # 关联专用服务账户
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      containers:
      - name: controller
        image: quay.io/metallb/controller:v0.13.7
        args:
        - --port=7472
        # - --metrics-addr=127.0.0.1:7472
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 7472
            host: 127.0.0.1
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 7472
            host: 127.0.0.1
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: speaker
  namespace: metallb-system
  labels:
    app: metallb
    component: speaker
spec:
  selector:
    matchLabels:
      app: metallb
      component: speaker
  template:
    metadata:
      labels:
        app: metallb
        component: speaker
    spec:
      hostNetwork: true
      serviceAccountName: speaker
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      containers:
      - name: speaker
        image: quay.io/metallb/speaker:v0.13.7
        args:
          - --port=7472
          - --config-path=/etc/metallb/config
          - --log-level=info
          - --node-name=$(NODE_NAME)
          - --host=0.0.0.0
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 7473
          name: monitoring
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 7473
            host: 127.0.0.1
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 7473
            host: 127.0.0.1
          initialDelaySeconds: 5
          periodSeconds: 10
    