apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-deployment
  namespace: default
  labels:
    app: pod-configurator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-configurator
  template:
    metadata:
      labels:
        app: pod-configurator
    spec:
      serviceAccountName: pod-configurator-sa
      containers:
      - name: configurator
        image: pod-configurator:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DEPLOYMENT_NAME
          value: "manager-deployment"